name: "Lint on Commit Messages and Pull Requests Title Naming Conventions"

on:
  pull_request:
    branches:
      - main
      - release/*

permissions:
  contents: read
  pull-requests: read

jobs:
  pr-checks:
    secrets: inherit
    uses: aizon-shared/common-workflows/.github/workflows/pull-request-checks.yaml@v4
